version: '3'
services:
  composetestdb:
    tty: true
  wordpress:
    image: wordpress
    ports:
      - 5000:80
    environment:
       WORDPRESS_DB_PASSWORD: abc123
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
